apiVersion: v1
kind: Secret
metadata:
  name: radiolocal-secret
type: Opaque
data:
  DB_URL: bW9uZ29kYitzcnY6Ly9wZWhhcmpvaGFuOm51WjU1SUdvdGhmZXhackZAY2x1c3RlcjAud2thd25lOS5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
  JWT_SECRET: c3VwZXJzZWNyZXRrZXk=
