apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "userservice.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "userservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "userservice.name" . }}
    spec:
      containers:
        - name: userservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3001
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}